<?php
/* SE DEFINEN CONSTANTES PARA LOS CORREOS DE PRUEBA PARA EL ENVIO DE NOTIFICACION*/

// MAIL DEL SISTEMA 
define('MAIL_SISTEMA', 'sistemavaspa@gmail.com');
define('CONTRASENA_SISTEMA', 'vaspa1234');

